event/dpaa: fix header include
[ upstream commit 89cf958482288903ae3bce2ca2a3dac8329f13e6 ]

rte_cycles.h shall be included instead of rte_cycles_64.h

dpaa_eventdev.c:32:27:
fatal error: rte_cycles_64.h: No such file or directory

Fixes: 9caac5dd1e7f ("event/dpaa: introduce PMD")

Signed-off-by: Hemant Agrawal <hemant.agrawal@nxp.com>