power: fix some doxygen comments
[ upstream commit 58794bf8d2d577b18e8bd430fd6419274678b34e ]

Fix following syntax error reported by doxygen 1.9.5 version.

lib/power/rte_power.h:169: error: rte_power_freq_up has
@param documentation sections but no arguments
(warning treated as error, aborting now)

Fixes: d7937e2e3d12 ("power: initial import")

Signed-off-by: Jerin Jacob <jerinj@marvell.com>