kni: fix ethtool dev_open build error
Build error about dev_open() arguments similar to
commit 5c97df1243da ("kni: fix build for dev_open in Linux 5.0")
seen when building with RHEL 8.2 and ethtool enabled.

kernel/linux/kni/ethtool/ixgbe/ixgbe_ethtool.c:
In function ‘ixgbe_diag_test’:
kernel/linux/kni/ethtool/ixgbe/ixgbe_ethtool.c:1748:4:
error: too few arguments to function ‘dev_open’
    dev_open(netdev);
    ^~~~~~~~
kernel/linux/kni/ethtool/ixgbe/ixgbe_ethtool.c:18:
./include/linux/netdevice.h:2795:5: note: declared here
 int dev_open(struct net_device *dev, struct netlink_ext_ack *extack);
     ^~~~~~~~

This is because Linux kernel
commit 00f54e68924e ("net: core: dev: Add extack argument to dev_open()")
is backported to RHEL/CentOS since 8.1.

Extend the fix in
commit 5c97df1243da ("kni: fix build for dev_open in Linux 5.0")
to cover RHEL/CentOS 8.1 onwards.

Signed-off-by: Kevin Traynor <ktraynor@redhat.com>
Acked-by: Luca Boccassi <bluca@debian.org>