kni: fix ethtool pointer type build error
Build error about incompatbile-pointer-types similar to
commit 219bfcc05796 ("kni: fix build with Linux 5.1")
seen when building with RHEL 8.2 and ethtool enabled.

kernel/linux/kni/ethtool/igb/igb_main.c:2358:18:
error: initialization of ‘int (*)...
[-Werror=incompatible-pointer-types]
  .ndo_fdb_add  = igb_ndo_fdb_add,
                  ^~~~~~~~~~~~~~~

This is because Linux kernel
commit 87b0984ebfab ("net: Add extack argument to ndo_fdb_add()")
is backported to RHEL/CentOS since 8.1.

Extend the fix in
commit 219bfcc05796 ("kni: fix build with Linux 5.1")
to cover RHEL/CentOS 8.1 onwards.

Signed-off-by: Kevin Traynor <ktraynor@redhat.com>
Acked-by: Luca Boccassi <bluca@debian.org>