kni: fix ethtool build error on kernel 5.9
read_barrier_depends() is removed from kernel 5.9 as per Linux
commit 93fab07c2293 ("locking/barriers: Remove definitions for [smp_]read_barrier_depends()")

It is used by ethtool and produces an error when building on kernel 5.9:

/kernel/linux/kni/ethtool/igb/igb_main.c: In function ‘igb_clean_tx_irq’:
/dpdk-stable/kernel/linux/kni/ethtool/igb/igb_main.c:7067:3:
error: implicit declaration of function ‘read_barrier_depends’
[-Werror=implicit-function-declaration]
 7067 |   read_barrier_depends();
      |   ^~~~~~~~~~~~~~~~~~~~

Fix by replacing with rmb() as is done for < 2.6 kernels.

Signed-off-by: Kevin Traynor <ktraynor@redhat.com>