examples/multi_process: fix compilation
Fix compilation of examples/multi_process:

> examples/multi_process/client_server_mp/mp_server/main.c:68:4: error:
> implicit declaration of function ‘rte_ether_format_addr’;
> did you mean ‘ether_format_addr’? [-Werror=implicit-function-declaration]
>     rte_ether_format_addr(err_address,
>     ^~~~~~~~~~~~~~~~~~~~~

This failure happens after the backport of
commit a7500412fc5c ("examples/multi_process: fix build on Ubuntu
20.04"), which uses a function that does not exist in this branch. The
function was introduced by upstream commit 538da7a1cad2 ("net: add rte
prefix to ether functions"), and is just a renaming of an existing
function.

Fixes: a7500412fc5c ("examples/multi_process: fix build on Ubuntu 20.04")

Signed-off-by: Olivier Matz <olivier.matz@6wind.com>