app/test: fix build with musl libc
[ upstream commit 816d76c53e246b97ee6dfc8343efa5959ea7270d ]

Fix following build error with musl libc:

app/test/test_eal_flags.c:152:55: error:
'O_RDONLY' undeclared (first use in this function)
      fd = openat(dirfd(hugepage_dir), dirent->d_name, O_RDONLY);
                                                       ^~~~~~~~

Fixes: 45f1b6e8680a ("app: add new tests on eal flags")

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>