compressdev: fix missing space in log macro
[ upstream commit dfb90fbe6b2b11ecf3535286c8d418ba8cc5485c ]

Building with clang on FreeBSD with chkincs enabled, we get the
following error about a missing space:

lib/compressdev/rte_compressdev_internal.h:25:58: error:
invalid suffix on literal;
C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
        rte_log(RTE_LOG_ ## level, compressdev_logtype, "%s(): "fmt "\n", \

Adding in a space between the '"' and 'fmt' removes the error.

Fixes: ed7dd94f7f66 ("compressdev: add basic device management")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>