bus/dpaa: fix build with gcc 9.0
[ upstream commit 74f277101265ff3376c65270da2dcbc6d1325494 ]

build error:
In function ‘fman_if_init’,
    .../drivers/bus/dpaa/base/fman/fman.c:186:2:
    error: ‘strncpy’ output may be truncated copying 4095 bytes from a
           string of length 4095 [-Werror=stringop-truncation]
    strncpy(__if->node_path, dpa_node->full_name, PATH_MAX - 1);

strncpy may result a not null-terminated string,
replaced it with strlcpy

Fixes: 5b22cf744689 ("bus/dpaa: introducing FMan configurations")

Signed-off-by: Ferruh Yigit <ferruh.yigit@intel.com>