usertools: fix Python compatibility issue
For LTS release before 20.02 which should support both Python 2 and 3,
when running usertools/dpdk-devbind.py with Python 2,there'll be the
following error:

Traceback (most recent call last):
  File "usertools/dpdk-devbind.py", line 755, in <module>
    main()
  File "usertools/dpdk-devbind.py", line 743, in main
    check_modules()
  File "usertools/dpdk-devbind.py", line 198, in check_modules
    if module_is_loaded(mod["Name"]):
  File "usertools/dpdk-devbind.py", line 177, in module_is_loaded
    release = platform.uname().release
AttributeError: 'tuple' object has no attribute 'release'

The root cause is that Python 2 doesn't support
platform.uname().release, which is supported by Python 3.

Fixes: 1e794e710d18 ("usertools: fix binding built-in kernel driver")
Cc: stable@dpdk.org

Signed-off-by: Beilei Xing <beilei.xing@intel.com>