bus/fslmc: fix build with musl libc
[ upstream commit da1a31d92d65b88e068724da342ea46dfaa70036 ]

This fixes the following compile error with musl libc:

drivers/bus/fslmc/qbman/include/compat.h:41:10: error:
'stdout' undeclared (first use in this function)
   fflush(stdout); \
          ^~~~~~

Fixes: 531b17a780dc ("bus/fslmc: add QBMAN driver to bus")

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>